# Generated by Django 5.2.10 on 2026-01-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('template_id', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('sections', models.JSONField()),
                ('scoring_result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
